batch/urls.py
from django.urls import path
from . import views

app_name = 'batch'

urlpatterns = [
    path('new/<str:id>', views.new, name = 'new'),
    path('', views.detailAll, name = 'detailAll'),
    path('<str:id>', views.detailWithId, name = 'detailId')
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new', views.new, name = 'new'),
    path('update/<str:id>', views.update, name = 'update'),
    path('delete/<str:id>', views.delete, name = 'delete'),
    path('', views.all, name = 'all'),
]

pengiriman/urls.py
from django.urls import path
from . import views

app_name = 'pengiriman'

urlpatterns = [
    path('new', views.new, name = 'new'),
    path('status/new/<str:id>', views.statuscreate, name = 'statuscreate'),
    path('status/riwayat/<str:id>', views.status, name = 'status'),
    path('', views.all, name = 'all')
]

sidia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls', namespace = 'authentication')),
    path('batch/', include('batch.urls', namespace = 'batch')),
    path('faskes/', include('faskes.urls', namespace = 'faskes')),
    path('item/', include('item.urls', namespace = 'item')),
    path('pengiriman/', include('pengiriman.urls', namespace = 'pengiriman')),
    path('permohonan/', include('permohonan.urls', namespace = 'permohonan')),
    path('pesanan/', include('pesanan.urls', namespace = 'pesanan')),
    path('stok-faskes/', include('stokfaskes.urls', namespace = 'stokfaskes')),
    path('stok-warehouse/', include('stokwarehouse.urls', namespace = 'stokwarehouse')),
    path('warehouse/', include('warehouse.urls', namespace = 'warehouse')),
    path('', views.homepage)
]

pengiriman/models.py
from django.db import models

# Create your models here.

pengiriman/views.py
from django.shortcuts import render, redirect
from django.db import connection
import json
import datetime
# See 14d
def new(request):
    return render(request, 'pengiriman/new.html')

# See 14d
def all(request):
    return render(request, 'pengiriman/all.html')

# See 17c
def statuscreate(request, id):
    data = []
    context = {}

    if(request.session["role"] == "Admin Satgas"):
        if(request.method == "POST"):
            kodeStatusBatch = request.POST["kodeStatusBatch"]
            tanggal = f"{datetime.datetime.now():%Y-%m-%d}"
            with connection.cursor() as c:
                for batch in getAllBatchCodeInOnePermohonan(id):
                    command = "INSERT INTO RIWAYAT_STATUS_PENGIRIMAN(Kode_status_batch_pengiriman, Kode_batch, Tanggal) VALUES "
                    command += str((str(kodeStatusBatch), batch, tanggal))
                    c.execute(command)
            return render(request, 'pengiriman/statusnew.html')
        else:
            context["pilihanKodeStatus"] = getChoices(getLastUpdatedStatusBatch(id))
            context["kodeTransaksi"] = json.dumps(id)
            return render(request, 'pengiriman/statusnew.html', context)
    else:
        return redirect("/")

#Ambil Status Terakhir dari suatu permohonan di batch tertentu
#1 permohonan punya banyak batch dan perubahan status batch dilakukan serentak untuk 1 permohonan
def getLastUpdatedStatusBatch(id):
    with connection.cursor() as c:
        command = "select kode_status_batch_pengiriman from riwayat_status_pengiriman "
        command += f"where kode_batch in (select kode from batch_pengiriman where nomor_transaksi_sumber_daya = {id})"
        command += "order by tanggal desc"
        c.execute(command)
        kodeStatus = c.fetchone()
        return kodeStatus[0]

#Ambil kode-kode batch di 1 permohonan
def getAllBatchCodeInOnePermohonan(id):
    data = []
    with connection.cursor() as c:
        command = f"select kode from batch_pengiriman where nomor_transaksi_sumber_daya = {id}"
        c.execute(command)
        for i in c.fetchall():
            data.append(i[0])
        return data

def getChoices(currentStatus):
    choices = []
    if(currentStatus == "PRO"):
        choices.append("dalam perjalanan (OTW)")
    elif(currentStatus == "OTW"):
        choices.append("selesai (DLV)")
        choices.append("hilang (HLG)")
        choices.append("dikembalikan (RET)")
    return choices


# See 17d
def status(request, id):
    data = []
    context = {}
    if(request.session['role'] == "Admin Satgas"):
        with connection.cursor() as c:
            command = "select rsp.kode_status_batch_pengiriman, sbp.nama, bp.username_satgas, rsp.tanggal "
            command += "from transaksi_sumber_daya tsd, batch_pengiriman bp, riwayat_status_pengiriman rsp, status_batch_pengiriman sbp "
            command += f"where sbp.kode = rsp.kode_status_batch_pengiriman and bp.kode = rsp.kode_batch and tsd.nomor = bp.nomor_transaksi_sumber_daya and bp.nomor_transaksi_sumber_daya = {id}"
            command += "order by rsp.tanggal desc"
            c.execute(command)
            dataSQL = c.fetchall()
            
            counter = 0
            for i in dataSQL:
                counter += 1
                data.append((counter, i))
            context["nomorTransaksi"] = id
            context["data"] = data
        return render(request, 'pengiriman/statusriwayat.html', context)
    elif(request.session['role'] == "Petugas Distribusi"):
        username = request.session['username']
        with connection.cursor() as c:
            command = "select rsp.kode_status_batch_pengiriman, sbp.nama, bp.username_satgas, rsp.tanggal "
            command += "from transaksi_sumber_daya tsd, batch_pengiriman bp, riwayat_status_pengiriman rsp, status_batch_pengiriman sbp "
            command += f" where sbp.kode = rsp.kode_status_batch_pengiriman and bp.kode = rsp.kode_batch and tsd.nomor = bp.nomor_transaksi_sumber_daya and bp.username_petugas_distribusi = '{username}' and bp.nomor_transaksi_sumber_daya = {id}"
            command += "order by rsp.tanggal desc"
            c.execute(command)
            dataSQL = c.fetchall()
            
            counter = 0
            for i in dataSQL:
                counter += 1
                data.append((counter, i))
            context["nomorTransaksi"] = id
            context["data"] = data
            context["dataNull"] = len(data) == 0
        return render(request, 'pengiriman/statusriwayat.html', context)

    else:
        return redirect("/")

pengiriman/templates/pengiriman/all.html
{% extends 'shared/base.html' %}

{% block title %}

{% endblock title %}

{% block content %}
{% endblock content %}

pengiriman/templates/pengiriman/new.html
{% extends 'shared/base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

{% endblock content %}

pengiriman/templates/pengiriman/statusnew.html
{% extends 'shared/base.html' %}

{% block title %}
Create Status Batch Pengiriman
{% endblock title %}

{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center mt-3">
        <div class="col-9">
            <div class="text-center"><h3>UBAH STATUS BATCH PENGIRIMAN</h3></div>
            <br>
            <form id="form-add" method="POST">
                {% csrf_token %}
                <div class="mb-3 text-center">
                    <label for="kodeStatusBatchPengiriman" class="form-label">Status: </label>
                    <select class="form-select" aria-label="Default select example" onchange="changeValOption(this);" name="kodeStatusBatchPengiriman" id="kodeStatusBatchPengiriman">
                        <option selected disabled value="">Pilih Status: </option>
                        {% for i in pilihanKodeStatus %}
                        <option value="">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center">
                    <button class="btn btn-primary" type="submit">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function changeValOption(status){
        var text = status.options[status.selectedIndex].text
        if(text === "selesai (DLV)"){
            status.options[status.selectedIndex].value = "DLV"
        }else if(text === "hilang (HLG)"){
            status.options[status.selectedIndex].value = "HLG"
        }else if(text === "dikembalikan (RET)"){
            status.options[status.selectedIndex].value = "RET"
        }else if(text === "dalam perjalanan (OTW)"){
            status.options[status.selectedIndex].value = "OTW"
        }
    }
    var kodeTransaksi = JSON.parse("{{kodeTransaksi|escapejs}}")
    $('#form-add').submit((event) =>{
            event.preventDefault();
            if($('#kodeStatusBatchPengiriman').val() === null){
                alert("Pilih Status terlebih dahulu")
                return;
            }
            $.post(
                `/pengiriman/status/new/${kodeTransaksi}`, {
                    kodeStatusBatch: $('#kodeStatusBatchPengiriman').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                () => {
                window.location.href = '/pengiriman'
                }
            )
        })
</script>
{% endblock content %}

pengiriman/templates/pengiriman/statusriwayat.html
{% extends 'shared/base.html' %}

{% block title %}
Read Status Batch Pengiriman
{% endblock title %}

{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center mt-3">
        <div class="col-md-12">
            {% if dataNull %}
            <div class="text-center"><h3>TIDAK ADA DATA YANG DAPAT DITAMPILKAN</h3></div>
            {% else %}
            <div class="text-center"><h3>RIWAYAT STATUS BATCH PENGIRIMAN</h3></div>
            <h6>Nomor Transaksi: {{nomorTransaksi}}</h6>
            <h6>Riwayat status:</h6>
            <table class="table table-bordered">
                <thead>
                    <tr>
                      <th scope="col">No.</th>
                      <th scope="col">Kode Status</th>
                      <th scope="col">Status</th>
                      <th scope="col">Username Admin Satgas</th>
                      <th scope="col">Tanggal Persetujuan</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in data %}
                        <tr>
                            <td>{{i.0}}</td>
                            <td>{{i.1.0}}</td>
                            <td>{{i.1.1}}</td>
                            <td>{{i.1.2}}</td>
                            <td>{{i.1.3}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            {% endif %}
            <div class="text-center">
                <a href="{% url 'batch:detailAll' %}">
                    <button type="button" class="btn btn-dark btn-lg">KEMBALI</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}