item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new', views.new, name = 'new'),
    path('update/<str:id>', views.update, name = 'update'),
    path('delete/<str:id>', views.delete, name = 'delete'),
    path('', views.all, name = 'all'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls', namespace = 'authentication')),
    path('batch/', include('batch.urls', namespace = 'batch')),
    path('faskes/', include('faskes.urls', namespace = 'faskes')),
    path('item/', include('item.urls', namespace = 'item')),
    path('pengiriman/', include('pengiriman.urls', namespace = 'pengiriman')),
    path('permohonan/', include('permohonan.urls', namespace = 'permohonan')),
    path('pesanan/', include('pesanan.urls', namespace = 'pesanan')),
    path('stok-faskes/', include('stokfaskes.urls', namespace = 'stokfaskes')),
    path('stok-warehouse/', include('stokwarehouse.urls', namespace = 'stokwarehouse')),
    path('warehouse/', include('warehouse.urls', namespace = 'warehouse')),
    path('', views.homepage)
]

stokwarehouse/urls.py
from django.urls import path
from . import views

app_name = 'stokwarehouse'

urlpatterns = [
    path('new', views.new, name = 'new'),
    path('update/<str:id_lokasi>/<str:id_item>', views.update, name = 'update'),
    path('delete/<str:id_lokasi>/<str:id_item>', views.delete, name = 'delete'),
    path('', views.all, name = 'all')
]

stokwarehouse/models.py
from django.db import models

# Create your models here.

stokwarehouse/views.py
from django.shortcuts import render, redirect
from django.db import connection
import json

# See 15c
#Fetch data done and Add new stok_warehouse_provinsi done
def new(request):
    context = {}
    data = []
    data2 = []
    if(request.session["role"] == "Admin Satgas"):
        if(request.method == "POST"):
            idLokasi = request.POST['idLokasi']
            kodeItem = request.POST['kodeItem']
            jumlahItem = request.POST['jumlahItem']
            with connection.cursor() as c:
                command = "INSERT INTO STOK_WAREHOUSE_PROVINSI VALUES "
                command += str((str(idLokasi), jumlahItem, str(kodeItem)))
                c.execute(command)
            return redirect('stokwarehouse:all')
        else:
            with connection.cursor() as c:
                c.execute("select * from lokasi")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    alamat = x[5] + ", Kel. " + x[4] + ", Kec. " + x[3] + ", Kab/Kota " + x[2] + ", Prov " + x[1]
                    data.append((x[0], alamat))
                context["dataLokasi"] = data
                context["dataJsonLokasi"] = json.dumps(data)

                c.execute("select kode, nama from item_sumber_daya")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data2.append((x[0], x[1]))
                context["dataItem"] = data2
                context["dataJsonItem"] = json.dumps(data2)
            return render(request, 'stokwarehouse/new.html', context)
    else:
        return redirect('/')

# See 15d
# Untuk admin satgas bisa create, update, dan read semua stok warehouse pada satgas
# Petugas faskes hanya bisa read stok pada warehouse satgas yang sama dengan provinsi dari Faskes tersebut
def all(request):
    # Read stock -> 
    # Admin satgas bisa liat semua
    # Petugas Faskes hanya bisa melihat stock item sumber daya pada warehouse satgas yang sama dengan provinsi tersebut
    data = []
    context = {}
    if request.session["role"] == "Admin Satgas":
        with connection.cursor() as c:
            command = "select swp.*, lokasi.provinsi, lokasi.kabkot, isd.nama from stok_warehouse_provinsi swp "
            command += "left join warehouse_provinsi wp on swp.id_lokasi_warehouse = wp.id_lokasi "
            command += "left join lokasi on lokasi.id = wp.id_lokasi "
            command += "left join item_sumber_daya isd on isd.kode = swp.kode_item_sumber_daya;"
            c.execute(command)
            dataSQL = c.fetchall()
        dictLokasi = {}
        for i in dataSQL:
            if i[0] not in dictLokasi:
                dictLokasi[i[0]] = "Table Stock Warehouse Satgas Prov. " + i[3] + ", Kab./Kota " + i[4]
        context["dictLokasi"] = dictLokasi
        context["data"] = dataSQL
        context["dataJson"] = json.dumps(dataSQL)
        context["role"] = request.session["role"]
        return render(request, 'stokwarehouse/all.html', context)
    elif request.session["role"] == "Petugas Faskes":
        username = request.session["username"]
        with connection.cursor() as c:
            command = "select swp.*, l.provinsi, l.kabkot, isd.nama from stok_warehouse_provinsi as swp, item_sumber_daya as isd, lokasi as l"
            command += " where swp.kode_item_sumber_daya = isd.kode and swp.id_lokasi_warehouse = l.id"
            command += f" and swp.id_lokasi_warehouse in (select id_lokasi from faskes where username_petugas = '{username}' and id_lokasi = swp.id_lokasi_warehouse)"
            c.execute(command)
            dataSQL = c.fetchall()
        dictLokasi = {}
        for i in dataSQL:
            if i[0] not in dictLokasi:
                dictLokasi[i[0]] = "Table Stock Warehouse Satgas Prov. " + i[3] + ", Kab./Kota " + i[4]
        context["dictLokasi"] = dictLokasi
        context["data"] = dataSQL
        context["dataJson"] = json.dumps(dataSQL)
        context["role"] = request.session["role"]
        return render(request, 'stokwarehouse/all.html', context)

# See 15e
def update(request, id_lokasi, id_item):
    data = []
    context = {}
    if request.session["role"] == "Admin Satgas":
        if(request.method == "POST"):
            jumlahItem = request.POST['jumlahItem']
            with connection.cursor() as c:
                command = f"update stok_warehouse_provinsi set jumlah = {jumlahItem} "
                command += f"where id_lokasi_warehouse = '{id_lokasi}' and kode_item_sumber_daya = '{id_item}'"
                c.execute(command)
            return redirect('stokwarehouse:all')
        else:
            with connection.cursor() as c:
                command = f"select * from stok_warehouse_provinsi where id_lokasi_warehouse = '{id_lokasi}' and kode_item_sumber_daya = '{id_item}'"
                c.execute(command)
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data.append((x))
                
                commandLokasi = f"select * from lokasi where id = '{id_lokasi}'"
                c.execute(commandLokasi)
                dataSQL2 = c.fetchone()
                dataLokasi = dataSQL2[5] + ", Kel. " + dataSQL2[4] + ", Kec. " + dataSQL2[3] + ", Kab/Kota " + dataSQL2[2] + ", Prov " + dataSQL2[1]

                commandItem = f"select nama from item_sumber_daya where kode = '{id_item}'"
                c.execute(commandItem)
                dataSQL3 = c.fetchone()
                dataItem = dataSQL3[0]

            context["data"] = data
            context["lokasi"] = dataLokasi
            context["item"] = dataItem
            return render(request, 'stokwarehouse/update.html', context)
    else:
        return redirect('/')


def delete(request, id_lokasi, id_item):
    if request.session["role"] == "Admin Satgas":
        with connection.cursor() as c:
            command = f"delete from stok_warehouse_provinsi where id_lokasi_warehouse = '{id_lokasi}' and kode_item_sumber_daya = '{id_item}'"
            c.execute(command)
        return render(request, 'stokwarehouse/all.html')
    else:
        return redirect('/')

stokwarehouse/templates/stokwarehouse/all.html
{% extends 'shared/base.html' %}

{% block title %}
All Stok Warehouse
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row justify-content-center">
            <div class="text-center pt-3 pb-3">
                {% if role == "Admin Satgas" %}
                    <a href="{% url 'stokwarehouse:new' %}">
                        <button type="button" class="btn btn-success btn-lg">Buat Stok Warehouse Baru</button>
                    </a>
                {% endif %}
            </div>
            <div class="col-12 pt-3">
                {% for key, value in dictLokasi.items %}
                {% csrf_token %}
                <div class="text-center" id="judulTable" ><h3>{{value}}</h3></div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                          <th scope="col">Item Sumber Daya</th>
                          <th scope="col">Jumlah</th>
                          {% if role == "Admin Satgas" %}<th scope="col">Action</th>{% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                            {% if i.0 == key %}
                            <tr id="{{i.0}}-{{i.2}}">
                                <td scope="row">{{i.5}}</td>
                                <td>{{i.1}}</td>
                                {% if role == "Admin Satgas" %}
                                <td>
                                    <button type="button" onclick="updateStokWarehouse(this)" class="btn btn-primary">Update</button>
                                    <button type="button" onclick="deleteStokWarehouse(this)" class="btn btn-danger">Delete</button>
                                </td>
                                {% endif %}
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        function updateStokWarehouse(button){
            const rowId = button.parentElement.parentElement.id.split('-');
            const [idLokasiWarehouse, kodeItem] = rowId;
            window.location = `/stok-warehouse/update/${idLokasiWarehouse}/${kodeItem}`
        }

        function deleteStokWarehouse(button){
            const rowId = button.parentElement.parentElement.id.split('-');
            const [idLokasiWarehouse, kodeItem] = rowId;
            console.log("MASUK KESINI")
            $.post(
                `/stok-warehouse/delete/${idLokasiWarehouse}/${kodeItem}`,
                {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                () => {
                    location.reload()
                    alert("Data berhasil dihapus")
                }
            )

            
        }
    </script>
{% endblock content %}

stokwarehouse/templates/stokwarehouse/new.html
{% extends 'shared/base.html' %}
{% block title %}
Create Stokwarehouse
{% endblock title %}

{% block content %}
    <div class="container h-100">
        <div class="row h-100 justify-content-center">
            <div class="col-9">
                <div class="text-center"><h1>FORM TAMBAH STOCK WAREHOUSE SATGAS</h1></div>
                <form id="form-add" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="idLokasi" class="form-label">Id Lokasi: </label>
                        <select class="form-select" aria-label="Default select example" name="idLokasi" id="idLokasi">
                            <option selected disabled value="">Pilih Lokasi: </option>
                            {% for i in dataLokasi %}
                            <option value="{{ i.0 }}">{{ i.0 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="lokasi" class="form-label">Lokasi: </label>
                        <input class="form-control" type="text" placeholder="Pilih Kode Lokasi terlebih dahulu" aria-label="Disabled input example" id="lokasi" disabled readonly>
                    </div>
                    <div class="mb-3">
                        <label for="kodeItem" class="form-label">Kode Item: </label>
                        <select class="form-select" aria-label="Default select example" name="kodeItem" id="kodeItem">
                            <option selected disabled value="">Pilih Kode Item Sumber Daya:</option>
                            {% for i in dataItem %}
                            <option value="{{ i.0 }}">{{ i.0 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="itemSumberDaya" class="form-label">Item Sumber Daya: </label>
                        <input class="form-control" type="text" placeholder="Pilih Kode Item Sumber Daya terlebih dahulu" aria-label="Disabled input example" id="itemSumberDaya" disabled readonly>
                    </div>

                    <div class="mb-3">
                        <label for="jumlahItem" class="form-label">Jumlah: </label>
                        <input type="number" class="form-control" id="jumlahItem" name="jumlahItem" placeholder="Masukkan jumlah item" min=0>
                    </div>
                    <div class="align-items-center">
                        <button class="btn btn-primary" type="submit">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>

        var data = JSON.parse("{{dataJsonLokasi|escapejs}}")
        var data2 = JSON.parse("{{dataJsonItem|escapejs}}")
        $(document).ready(function(){
            $("#idLokasi").on("change", function(){
                var id = $(this).val();
                for(var i = 0; i < data.length; i++){
                    if(data[i][0] === id){
                        $("#lokasi").val(data[i][1])
                    }
                }
            })

            $("#kodeItem").on("change", function(){
                var id = $(this).val();
                for(var i = 0; i < data2.length; i++){
                    if(data2[i][0] === id){
                        $("#itemSumberDaya").val(data2[i][1])
                    }
                }
            })
        });

        $('#form-add').submit((event) =>{
            event.preventDefault();
            console.log($('#idLokasi').val())
            console.log($('#kodeItem').val())
            console.log($('#jumlahItem').val())
            if ($('#idLokasi').val() == null){
                alert('Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
                return;
            }

            if ($('#kodeItem').val() == null){
                alert('Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
                return;
            }

            if ($('#jumlahItem').val() == ""){
                alert('Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
                return;
            }

            $.post(
                `/stok-warehouse/new`,{
                    idLokasi: $('#idLokasi').val(),
                    kodeItem: $('#kodeItem').val(),
                    jumlahItem: $('#jumlahItem').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                () => {
                    window.location.href = '/stok-warehouse'
                }
            )
        })
    </script>
{% endblock content %}

stokwarehouse/templates/stokwarehouse/update.html
{% extends 'shared/base.html' %}

{% block title %}
Update Stokwarehouse
{% endblock title %}

{% block content %}
<div class="container h-100">
    <div class="row h-100 justify-content-center">
        <div class="col-9">
            <div class="text-center"><h1>FORM UBAH STOCK WAREHOUSE SATGAS</h1></div>
            <form id="form-update" method="POST">
                {% csrf_token %}
                {% for i in data %}
                <div class="mb-3">
                    <label for="idLokasi" class="form-label">Id Lokasi: </label>
                    <input type="text" class="form-control" id="idLokasi" name="idLokasi" disabled required value="{{i.0}}">
                </div>
                <div class="mb-3">
                    <label for="lokasi" class="form-label">Lokasi: </label>
                    <input class="form-control" type="text" value="{{lokasi}}" aria-label="Disabled input example" id="lokasi" disabled readonly>
                </div>
                <div class="mb-3">
                    <label for="kodeItem" class="form-label">Kode Item: </label>
                    <input type="text" class="form-control" id="kodeItem" name="kodeItem" disabled required value="{{i.2}}">
                </div>
                <div class="mb-3">
                    <label for="itemSumberDaya" class="form-label">Item Sumber Daya: </label>
                    <input class="form-control" type="text" value="{{item}}" aria-label="Disabled input example" id="itemSumberDaya" disabled readonly>
                </div>

                <div class="mb-3">
                    <label for="jumlahItem" class="form-label">Jumlah: </label>
                    <input type="number" class="form-control" id="jumlahItem" name="jumlahItem" min=0 placeholder="Masukkan jumlah item" value="{{i.1}}">
                </div>
                <div class="align-items-center">
                    <button class="btn btn-primary" type="submit">Simpan</button>
                </div>
                {% endfor %}
            </form>
        </div>
    </div>
</div>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
    $('#form-update').submit((event) =>{
            event.preventDefault();
            console.log($('#idLokasi').val())
            console.log($('#kodeItem').val())
            console.log($('#jumlahItem').val())

            if ($('#jumlahItem').val() == ""){
                alert('Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu')
                return;
            }

            $.post(
                `/stok-warehouse/update/${$('#idLokasi').val()}/${$('#kodeItem').val()}`,{
                    jumlahItem: $('#jumlahItem').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                () => {
                    window.location.href = '/stok-warehouse'
                }
            )
        })
</script>
{% endblock content %}